name: water_net_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=2.2
  - scipy=1.11
  - matplotlib=3.8
  - seaborn=0.13
  - geopandas=0.14
  - cartopy=0.22
  - networkx=3.2
  - scikit-learn=1.4
  - statsmodels=0.14
  - plotly=5
  - xarray
  - dask
  - pip
  - pip:
      - upsetplot==0.9.0